### ISSUE TITLE
Rendering Issue

### ISSUE THREAD

**Issue by TimGoll** [TeamDmfMM/Catwalks-4#13]
Minecraft 1.12.2, newest version of your mod

![image](https://user-images.githubusercontent.com/13639408/45374747-50147b00-b5f3-11e8-9cae-36171a5ffd75.png)
At Z=0 the catwalks get rendered really strange. This problem is solved by enabling the optifine compatiblity option.

![image](https://user-images.githubusercontent.com/13639408/45374785-6f130d00-b5f3-11e8-9579-9bb9f2ce22c0.png)
Catlwalks are transparent if you look at the from the bottom. This problem is not solved by enabling the optifine compatibility option

**Comment by TimGoll** [comment]
Furthermore there is an error:

```
 CCL has caught an exception whilst rendering a block
  BlockPos:      x:205, y:82, z:-5
  Block Class:   class dmfmm.catwalks.block.CatwalkBlock
  Registry Name: catwalks:catwalk
  Metadata:      0
  State:         catwalks:catwalk[material=classic]
 Tile at position
  Tile Class:    class dmfmm.catwalks.tileentity.CatwalkTile
  Tile Id:       catwalks:catwalks
  Tile NBT:      {east:0b,material:"magneticraft_steel",south:0b,north:1b,x:205,west:1b,y:82,z:-5,id:"catwalks:catwalks",up:1b,down:1b}
```

**Comment by alexgurrola** [comment]
I'm getting the same from catwalk cable:

```
 CCL has caught an exception whilst rendering a block
  BlockPos:      x:-3, y:39, z:25
  Block Class:   class dmfmm.catwalks.block.CableBlock
  Registry Name: catwalks:cable
  Metadata:      0
  State:         catwalks:cable
 Tile at position
  Tile Class:    null
  Tile Id:       null
  Tile NBT:      null
```

**Comment by CritFlaw** [comment]
I think I'm getting the same 

```[14:38:35] [Chunk Batcher 13/ERROR]: 
 CCL has caught an exception whilst rendering a block
  BlockPos:      x:-1001, y:1, z:-1025
  Block Class:   class dmfmm.catwalks.block.CatwalkBlock
  Registry Name: catwalks:catwalk
  Metadata:      0
  State:         catwalks:catwalk[material=classic]
 Tile at position
  Tile Class:    class dmfmm.catwalks.tileentity.CatwalkTile
  Tile Id:       catwalks:catwalks
  Tile NBT:      {east:1b,material:"classic",south:0b,north:1b,x:-1001,west:1b,y:1,z:-1025,id:"catwalks:catwalks",up:1b,down:1b}
You can turn off player messages in the CCL config file.

net.minecraft.util.ReportedException: Tesselating block model
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:95) ~[bvm.class:?]
	at codechicken.lib.render.block.CCBlockRendererDispatcher.func_175018_a(CCBlockRendererDispatcher.java:82) [CCBlockRendererDispatcher.class:?]
	at com.elytradev.architecture.client.render.CustomBlockDispatcher.func_175018_a(CustomBlockDispatcher.java:98) [CustomBlockDispatcher.class:?]
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:327) [bxr.class:?]
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100) [bxn.class:?]
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:43) [bxn.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.NullPointerException
	at net.minecraft.client.renderer.BlockModelRenderer.func_187497_c(BlockModelRenderer.java:146) ~[bvo.class:?]
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187497_c(ForgeBlockModelRenderer.java:68) ~[ForgeBlockModelRenderer.class:?]
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:78) ~[bvo.class:?]
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:57) ~[bvo.class:?]
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:80) ~[bvm.class:?]
	... 6 more
[14:38:35] [Chunk Batcher 13/INFO]: [CHAT] CCL Caught an exception rendering a block. See the log for info.
[14:38:41] [Chunk Batcher 13/ERROR]: 
 CCL has caught an exception whilst rendering a block
  BlockPos:      x:-1002, y:1, z:-1013
  Block Class:   class dmfmm.catwalks.block.CatwalkBlock
  Registry Name: catwalks:catwalk
  Metadata:      0
  State:         catwalks:catwalk[material=classic]
 Tile at position
  Tile Class:    class dmfmm.catwalks.tileentity.CatwalkTile
  Tile Id:       catwalks:catwalks
  Tile NBT:      {east:0b,material:"classic",south:0b,north:0b,x:-1002,west:1b,y:1,z:-1013,id:"catwalks:catwalks",up:1b,down:1b}
You can turn off player messages in the CCL config file.

net.minecraft.util.ReportedException: Tesselating block model
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:95) ~[bvm.class:?]
	at codechicken.lib.render.block.CCBlockRendererDispatcher.func_175018_a(CCBlockRendererDispatcher.java:82) [CCBlockRendererDispatcher.class:?]
	at com.elytradev.architecture.client.render.CustomBlockDispatcher.func_175018_a(CustomBlockDispatcher.java:98) [CustomBlockDispatcher.class:?]
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:327) [bxr.class:?]
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100) [bxn.class:?]
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:43) [bxn.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.NullPointerException
	at net.minecraft.client.renderer.BlockModelRenderer.func_187497_c(BlockModelRenderer.java:146) ~[bvo.class:?]
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187497_c(ForgeBlockModelRenderer.java:68) ~[ForgeBlockModelRenderer.class:?]
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:78) ~[bvo.class:?]
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:57) ~[bvo.class:?]
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:80) ~[bvm.class:?]
```

**Comment by SatyrRex** [comment]
This is still a thing.


```
[15:25:44] [Chunk Batcher 14/ERROR] [CodeChickenLib]: 
 CCL has caught an exception whilst rendering a block
  BlockPos:      x:-488, y:70, z:2852
  Block Class:   class dmfmm.catwalks.block.CatwalkBlock
  Registry Name: catwalks:catwalk
  Metadata:      0
  State:         catwalks:catwalk[material=classic]
 Tile at position
  Tile Class:    class dmfmm.catwalks.tileentity.CatwalkTile
  Tile Id:       catwalks:catwalks
  Tile NBT:      {east:1b,material:"classic",south:0b,north:0b,x:-488,west:1b,y:70,z:2852,id:"catwalks:catwalks",up:1b,down:1b}
You can turn off player messages in the CCL config file.

net.minecraft.util.ReportedException: Tesselating block model
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:95) ~[bvm.class:?]
	at codechicken.lib.render.block.CCBlockRendererDispatcher.func_175018_a(CCBlockRendererDispatcher.java:82) [CCBlockRendererDispatcher.class:?]
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:200) [bxr.class:?]
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100) [bxn.class:?]
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:43) [bxn.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.NullPointerException

```
